# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_ismi', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=255)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=255)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Çalışanlar',
            },
        ),
        migrations.CreateModel(
            name='Sales_Slip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasa_fisi_zamani', models.DateTimeField(default=django.utils.timezone.now)),
                ('calisanlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbella.Employee')),
                ('musteriler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbella.Customer')),
            ],
            options={
                'verbose_name_plural': 'Kasa Fişi',
            },
        ),
        migrations.CreateModel(
            name='Sales_Slip_Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Kasa Fişi Raporu',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmet_ismi', models.CharField(max_length=255)),
                ('hizmet_detayi', models.CharField(max_length=255)),
                ('hizmet_fiyati', models.DecimalField(decimal_places=1, max_digits=9)),
                ('kategoriler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbella.Category')),
            ],
            options={
                'verbose_name_plural': 'Hizmetler',
            },
        ),
        migrations.AddField(
            model_name='sales_slip_action',
            name='hizmetler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbella.Services'),
        ),
        migrations.AddField(
            model_name='sales_slip_action',
            name='kasa_fisi_zamani',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbella.Sales_Slip'),
        ),
    ]
