# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0002_auto_20160902_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='kullanici_adi',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='mail',
        ),
    ]
