# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0004_user_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='mbella.User'),
        ),
    ]
