# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 21:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0015_auto_20160905_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='eklenme_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 21, 24, 58, 549395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sales_slip',
            name='kasa_fisi_zamani',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 21, 24, 58, 553271, tzinfo=utc)),
        ),
    ]
