# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0015_auto_20160905_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dogum_tarihi',
            field=models.DateField(default=0, null=True),
        ),
    ]
