# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0016_auto_20160909_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dogum_tarihi',
            field=models.DateField(null=True),
        ),
    ]
