# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0018_auto_20160907_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='eklenme_tarihi',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
