# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0019_auto_20160907_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='eklenme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
