# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0020_auto_20160907_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_slip',
            name='kasa_fisi_zamani',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
