# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0023_auto_20160907_0120'),
        ('mbella', '0018_auto_20160909_1029'),
    ]

    operations = [
    ]
