# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 12:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0024_merge_20160922_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='eklenme_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 22, 12, 32, 26, 807622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sales_slip',
            name='kasa_fisi_zamani',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 22, 12, 32, 26, 809987, tzinfo=utc)),
        ),
    ]
