# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mbella', '0025_auto_20160922_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parola',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='eklenme_tarihi',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 23, 7, 33, 22, 804300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sales_slip',
            name='kasa_fisi_zamani',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 23, 7, 33, 22, 806507, tzinfo=utc)),
        ),
    ]
